### ISSUE TITLE
[QUESTION] Use for live migration

### ISSUE THREAD

**Issue by lmeyerov** [neo4j-field/neo4j-arrow#1]
Howdy, we have a Project Domino (#graph4good) migration project where it may be fun to kick the tires here :)

Setup:
- Server 1: Live legacy database 1 (rather not turn off) - community edition docker in 3.x neo4j. About a ~0.5B node/edge graph with a few indexes. Nodes have a `created_at` field. Something like 1M nodes/edges a day.
- Server 2: Target new database 2 (4.x community edition docker, whatever we want)

Goal:
- Standup DB clone 2 without having to stop DB 1, and when sufficiently happy, switch to Server 2. Ok if a bit of drift near the end.

Idea: Two stage pipeline -
Stage 1: Streaming Remote dump - live stream nodes/edges to time-indexed parquet chunks (edges.parquet, nodes.parquet).  Legacy neo4j, so just use the python driver from a remote system. No realistic way to use neo4j-arrow due to not being able muck with the legacy db...

Stage 2: Bulk Import - Parquet -> Neo4j via arrow. Initial benefit is easier ingest experimentation in case issues at bigger sizes. (We had similar projects take hours/days via normal neo4j loaders, which was frustrating when data quality issues.)

Would this make sense, and any recommendations for making the process easier, e.g., parquet format, version numbers, ...

**Comment by lmeyerov** [comment]
Quick update: apparently we're on enterprise 4.0.x, which has remote online backups, so curious which would make more sense...

**Comment by voutilad** [comment]
My current focus is on analytic workloads with the [GDS](https://github.com/neo4j/graph-data-science) in-memory graph format. From what I'm seeing, Arrow can help in a lot of places, but my focus is rapid construction and migration of GDS graphs.

Migrating the database itself is best done through the Neo4j Enterprise online backup service or using the existing clustering semantics. Can Arrow make this better? Maybe. I do think there could be some room for overhauling the property store as it would make the most sense in a columnar format like Arrow.
