### ISSUE TITLE
Request: add driver installation details in README

### ISSUE THREAD

**Issue by emigre459** [neo4j-field/neo4j-arrow#3]
Thanks for getting this project started, I'm very excited for its potential! I'm curious about how best to use the python driver, as I don't see any `setup.py` for that driver to do a typical package install. Do you intend for it to just drop into a project and be used locally, or added as a module to an existing package?

**Comment by voutilad** [comment]
Yes, drop a copy of the file in. I don’t intend to distribute via PyPI, but eventually may have a git-based way to pip install.
